language: python

python:
  - 3.5

notifications:
  email:
    on_success: change
    on_failure: change

install:
  - pip install -r requirements.txt
  - pip install pep8

script:
  - pep8 --count --show-source --exclude=migrations,manage.py saskatoon/